"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _landing_greeting from './landing-greeting.bones.json'
import _landing_cards from './landing-cards.bones.json'

registerBones({
  "landing-greeting": _landing_greeting,
  "landing-cards": _landing_cards,
})
